version: '3.9'
services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - 'back'

  back:
    build: ./back
    env_file: .env
    depends_on:
      - 'db'

  db:
    image: postgres
    restart: always
    ports:
      - '5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ft_transcendence

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
