version: '3.8'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env.dev
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
 #     - ./db:/docker-entrypoint-initdb.d/


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local