export const BACK_URL = "http://localhost:4000";

export const BACK_WIN_WIDTH = 1000;
export const BACK_WIN_HEIGHT = 500;
export const FRAME_RATE = 400; //data sent FRAME_RATE time per second
export const GOAL_DELAY = FRAME_RATE / 2;
export const BACK_BALL_SIZE = 6;
export const DEFAULT_BALL_SPEED = 1;
export const STARTINGPOS_LEFT_X = BACK_WIN_WIDTH / 20;
export const STARTINGPOS_RIGHT_X = (BACK_WIN_WIDTH / 20) * 19;
export const PADDLE_HEIGHT = BACK_WIN_HEIGHT / 15;
export const PADDLE_WIDTH = BACK_WIN_WIDTH / 120;
export const NO_NEW_FRAME = 10; 
export const SCORE_LIMIT = 20;
export const RECONNECTION_DELAY = 2 //seconds
export const POWERUPDELAY = FRAME_RATE * 7 // un nouveau powerup apparait toutes les 7 secondes
export const POWERUPDURATION = FRAME_RATE * 5 //temps actif d'un powerup
export const POWERUPSCALE = 34
export const STOPWATCHSCALE = 12